### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by josephgupkim** [helloimstephan/intro-data-capstone-biodiversity#1]
Structure
I appreciated the efficient structure of your project as it created an understandable flow of information between each slide and seemed to be broken down in a way that was easy to follow.

Visual
I liked the aesthetics of your project as it wasn’t too much to look at (easy on the eyes) and the color/font choices were appropriate. I also though the inclusion of visual aids, such as the graphs and charts, were helpful in the explanation of the data.

Quality
The overall quality of your analysis was to a high degree as it was detailed and explained well. You were able to further clarify how you came upon certain conclusions with the addition of formulas, calculations, and thorough explanations. Awesome job!

Grade: Meets expectation, keep up the good work!

**Comment by helloimstephan** [comment]
Thank you very much for your feedback and kind words!
